project: coconut
save_path: ./checkpoints
name: prosqa-coconut

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False

# Dataset paths
train_path: ./data/prosqa_train.json
val_path: ./data/prosqa_valid.json
test_path: ./data/prosqa_test.json

# Training parameters
batch_size_training: 2
num_epochs: 5
lr: 0.0001
